### ISSUE TITLE
calendar view tab

### ISSUE THREAD

**Issue by jonsflow** [jonathanalexander229/rh_web#4]
I'll create a calendar month view that shows daily closed profit and loss. Here are the necessary code changes:

## 1. Add a new tab to index.html

```html
<!-- Add to the tabs section, line ~82 -->
<div class="tab" data-tab="calendarView">P&L Calendar</div>

<!-- Add this new tab content section -->
<div id="calendarView" class="tab-content">
    <div class="filters">
        <div class="filter-row">
            <select id="calendarYearMonth">
                <!-- Options will be filled by JS -->
            </select>
            <button id="resetCalendarFilters">Reset</button>
        </div>
    </div>
    
    <div id="calendarContainer" class="calendar-container">
        <!-- Calendar will be rendered here -->
    </div>
</div>
```

## 2. Add CSS for calendar view in styles.css

```css
/* Add calendar styles */
.calendar-container {
    margin-top: 20px;
}

.calendar-month {
    display: grid;
    grid-template-columns: repeat(7, 1fr);
    gap: 5px;
    background-color: white;
    border-radius: 5px;
    padding: 15px;
    box-shadow: 0 2px 5px rgba(0,0,0,0.1);
}

.calendar-header {
    font-weight: bold;
    text-align: center;
    padding: 10px;
    background-color: #f1f1f1;
}

.calendar-day {
    min-height: 100px;
    padding: 10px;
    border: 1px solid #ddd;
    border-radius: 4px;
    display: flex;
    flex-direction: column;
}

.calendar-day.inactive {
    background-color: #f5f5f5;
    color: #bbb;
}

.calendar-day-number {
    font-weight: bold;
    margin-bottom: 5px;
}

.calendar-day-profit {
    color: #00C805;
    font-weight: bold;
}

.calendar-day-loss {
    color: #FF5000;
    font-weight: bold;
}

.daily-pl-total {
    margin-top: auto;
    padding-top: 10px;
    border-top: 1px dotted #ddd;
}

.trade-item {
    font-size: 12px;
    margin: 2px 0;
    white-space: nowrap;
    overflow: hidden;
    text-overflow: ellipsis;
}
```

## 3. Create a new calendar.js file

```javascript
// calendar.js - Handles rendering and interaction with P&L calendar view

let availableMonths = [];

// Format currency
function formatCurrency(value) {
    if (!value) return '$0.00';
    const sign = value >= 0 ? '+' : '';
    return sign + '$' + Math.abs(value).toFixed(2);
}

// Calculate daily P&L from closed positions
function calculateDailyPL() {
    const dailyPL = {};
    
    // Process closed positions
    optionsData.closed_positions.forEach(position => {
        if (!position.close_date) return;
        
        // Extract date part only
        const closeDate = position.close_date.split(' ')[0];
        const netCredit = position.net_credit || 0;
        
        if (!dailyPL[closeDate]) {
            dailyPL[closeDate] = {
                total: 0,
                trades: []
            };
        }
        
        // Add to daily total
        dailyPL[closeDate].total += netCredit;
        
        // Add trade details
        dailyPL[closeDate].trades.push({
            symbol: position.symbol,
            strategy: position.strategy || 'Unknown',
            strike: position.strike_price || '',
            pl: netCredit
        });
    });
    
    return dailyPL;
}

// Generate available year-month options
function generateAvailableMonths() {
    const months = new Set();
    
    optionsData.closed_positions.forEach(position => {
        if (!position.close_date) return;
        
        // Extract year-month part only
        const closeDate = position.close_date.split(' ')[0];
        const yearMonth = closeDate.substring(0, 7); // YYYY-MM format
        months.add(yearMonth);
    });
    
    // Convert to array and sort
    availableMonths = Array.from(months).sort().reverse();
    
    // Populate dropdown
    const select = document.getElementById('calendarYearMonth');
    select.innerHTML = '';
    
    availableMonths.forEach(month => {
        const option = document.createElement('option');
        option.value = month;
        
        // Format as Month YYYY
        const date = new Date(month + '-01');
        option.textContent = date.toLocaleDateString(undefined, { 
            year: 'numeric', 
            month: 'long' 
        });
        
        select.appendChild(option);
    });
    
    // Default to most recent month
    if (availableMonths.length > 0) {
        select.value = availableMonths[0];
    }
}

// Render calendar for a specific month
function renderCalendar() {
    const container = document.getElementById('calendarContainer');
    const selectedMonth = document.getElementById('calendarYearMonth').value;
    
    // If no month selected or no data, show message
    if (!selectedMonth || availableMonths.length === 0) {
        container.innerHTML = '<div class="empty-message">No closed trades found</div>';
        return;
    }
    
    // Calculate daily P&L
    const dailyPL = calculateDailyPL();
    
    // Create date object for selected month
    const [year, month] = selectedMonth.split('-');
    const date = new Date(parseInt(year), parseInt(month) - 1, 1);
    
    // Calculate month details
    const monthName = date.toLocaleDateString(undefined, { month: 'long', year: 'numeric' });
    const daysInMonth = new Date(date.getFullYear(), date.getMonth() + 1, 0).getDate();
    const firstDayOfMonth = new Date(date.getFullYear(), date.getMonth(), 1).getDay();
    
    // Create calendar HTML
    let calendarHTML = `
        <h2>${monthName}</h2>
        <div class="calendar-month">
            <div class="calendar-header">Sun</div>
            <div class="calendar-header">Mon</div>
            <div class="calendar-header">Tue</div>
            <div class="calendar-header">Wed</div>
            <div class="calendar-header">Thu</div>
            <div class="calendar-header">Fri</div>
            <div class="calendar-header">Sat</div>
    `;
    
    // Add empty cells for days before start of month
    for (let i = 0; i < firstDayOfMonth; i++) {
        calendarHTML += '<div class="calendar-day inactive"></div>';
    }
    
    // Add days of the month
    let monthlyTotal = 0;
    
    for (let day = 1; day <= daysInMonth; day++) {
        const dayDate = `${year}-${month.padStart(2, '0')}-${day.toString().padStart(2, '0')}`;
        const dayData = dailyPL[dayDate];
        const hasTrades = dayData && dayData.trades.length > 0;
        const dayTotal = dayData ? dayData.total : 0;
        
        // Add to monthly total
        monthlyTotal += dayTotal;
        
        // Determine CSS class for profit/loss
        const plClass = dayTotal > 0 ? 'calendar-day-profit' : 
                       dayTotal < 0 ? 'calendar-day-loss' : '';
        
        calendarHTML += `
            <div class="calendar-day">
                <div class="calendar-day-number">${day}</div>
                ${hasTrades ? `
                    <div class="trades-container">
                        ${dayData.trades.slice(0, 3).map(trade => `
                            <div class="trade-item" title="${trade.symbol} ${trade.strategy} ${trade.strike} - ${formatCurrency(trade.pl)}">
                                ${trade.symbol}: ${formatCurrency(trade.pl)}
                            </div>
                        `).join('')}
                        ${dayData.trades.length > 3 ? `<div class="trade-item">+ ${dayData.trades.length - 3} more</div>` : ''}
                    </div>
                    <div class="daily-pl-total ${plClass}">
                        Total: ${formatCurrency(dayTotal)}
                    </div>
                ` : ''}
            </div>
        `;
    }
    
    // Add empty cells for days after end of month
    const lastDayOfMonth = new Date(date.getFullYear(), date.getMonth(), daysInMonth).getDay();
    const remainingCells = 6 - lastDayOfMonth;
    
    for (let i = 0; i < remainingCells; i++) {
        calendarHTML += '<div class="calendar-day inactive"></div>';
    }
    
    calendarHTML += '</div>';
    
    // Add monthly summary
    const monthlyClass = monthlyTotal > 0 ? 'profit' : monthlyTotal < 0 ? 'loss' : '';
    calendarHTML += `
        <div class="summary-card" style="margin-top: 20px;">
            <h3>Monthly P&L</h3>
            <div class="value ${monthlyClass}">
                ${formatCurrency(monthlyTotal)}
            </div>
        </div>
    `;
    
    container.innerHTML = calendarHTML;
}

// Setup calendar event listeners
function setupCalendarListeners() {
    document.getElementById('calendarYearMonth').addEventListener('change', renderCalendar);
    document.getElementById('resetCalendarFilters').addEventListener('click', () => {
        document.getElementById('calendarYearMonth').value = availableMonths[0] || '';
        renderCalendar();
    });
}

// Initialize calendar
function initCalendar() {
    generateAvailableMonths();
    setupCalendarListeners();
    renderCalendar();
}
```

## 4. Update main.js to initialize the calendar

```javascript
// Update the renderDashboard function - add calendar initialization
function renderDashboard() {
    renderSummary();
    renderOpenPositions();
    renderClosedPositions();
    renderExpiredPositions();
    renderAllOrders();
    initCalendar(); // Add this line
    populateFilters();
    setupSortListeners();
}
```

## 5. Update index.html to include the new script

```html
<!-- Add this before the closing </body> tag -->
<script src="/static/js/calendar.js"></script>
```

This implementation creates a monthly calendar view showing:
- Daily closed P&L totals
- Individual trades for each day
- Color-coded profit/loss indicators
- A monthly total at the bottom
- Dropdown to select different months with data

You can navigate between different months to see your trading performance over time. The calendar will only display months that have closed trades.
